services:
  - type: web
    name: Personal_Finances_DRF
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn PersonalFinances.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: PersonalFinancesAPIPostgreSQL
          property: connectionString
      - key: SECRET_KEY
        value: tu_clave_secreta
      - key: DEBUG
        value: "False"