# Generated by Django 5.1.6 on 2025-02-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_budget_amount_budget_remaining_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='remaining_budget',
        ),
        migrations.AddField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.budget'),
        ),
    ]
