# Generated by Django 5.1.6 on 2025-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_remove_budget_remaining_budget_transaction_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
