# Generated by Django 5.1.6 on 2025-02-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_transaction_amount_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='goal_end_date',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='amount_goal',
        ),
        migrations.AddField(
            model_name='goals',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='in_progress', max_length=12),
        ),
        migrations.AddField(
            model_name='goals',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.goals'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
