# Generated by Django 5.1.6 on 2025-03-04 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_rename_goal_end_date_goals_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.goals'),
        ),
    ]
