# Generated by Django 5.1.6 on 2025-03-07 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='split',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SplitTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.category')),
                ('parent_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='finances.transaction')),
            ],
        ),
    ]
