# Generated by Django 5.1.6 on 2025-03-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_alter_category_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recurring_transaction', to='finances.category'),
        ),
    ]
